# Building & releasing Electron w/ Travis https://studiolacosanostra.github.io/2019/03/26/Automate-electron-app-release-build-on-github-with-Travis-CI/
# Env variables for electron-builder codesigning https://www.electron.build/code-signing

language: node_js
node_js: "10"

# Multiple operating systems
# https://docs.travis-ci.com/user/multi-os/
os:
  - osx
    osx_image: xcode10.2
  - linux
    services: docker
    language: generic
# os: osx
# osx_image: xcode10.2

stages: 
  - test
  - build
    if: branch != master
  - release
    if: branch = master

# Staged jobs
# https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages
jobs:
  include:
    - stage: test
      os: linux
      script:
        - yarn test

    - stage: build
      name: "Mac"
      os: osx
      script: yarn run build
    - name: "Windows"
      os: linux
      script: yarn run build
      script: 
        - |
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          docker run --rm \
          -e GH_TOKEN=$GH_TOKEN \
          -v $PWD:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "yarn install --link-duplicates --pure-lockfile && yarn run build"
        fi

    - stage: release
      name: "Mac"
      os: osx
      script: yarn run release
    - name: "Windows"
      os: linux
      script: 
        - |
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          docker run --rm \
          -e GH_TOKEN=$GH_TOKEN \
          -v $PWD:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "yarn install --link-duplicates --pure-lockfile && yarn run release"
        fi


    # - stage: Build Mac
    #   if: (branch != master) AND (branch != stable)
    #   script:
    #     - yarn run build
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine
    # - stage: Build Windows
    #   script:
    #     - yarn run build
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine
    # - stage: Release — Build Mac, Notarize, Deploy to Github Release 
    #   if: (branch = master) OR (branch = stable)
    #   script:
    #     - yarn run release
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine


# Remove Wine
before_cache: rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder  

# Run on all branches (and PRs)
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"