# Building & releasing Electron w/ Travis https://studiolacosanostra.github.io/2019/03/26/Automate-electron-app-release-build-on-github-with-Travis-CI/
# Env variables for electron-builder codesigning https://www.electron.build/code-signing

language: node_js
node_js: "10"

# Multiple operating systems
# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx
    osx_image: xcode10.2
# os: osx
# osx_image: xcode10.2

# Remove Wine for Windows build
before_cache:
  - if ["$TRAVIS_OS_NAME" = "linux"]; rm -rf $HOME/.cache/electron-builder/wine; fi

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder  

# Run on all branches (and PRs)
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
  # only:
  # - master
  # - dev

# Staged jobs
# https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages
jobs:
  include:
    - stage: "Tests"
      os: linux
      script:
        - yarn test

    - stage: "Build"
      name: "Mac"
      os: osx
      if: branch != master
      script: yarn run build
    - name: "Windows"
      os: linux
      script: yarn run build

    - stage: "Release to Github"
      if: branch = master
      os: osx
      script: yarn run release


    # - stage: Build Mac
    #   if: (branch != master) AND (branch != stable)
    #   script:
    #     - yarn run build
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine
    # - stage: Build Windows
    #   script:
    #     - yarn run build
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine
    # - stage: Release — Build Mac, Notarize, Deploy to Github Release 
    #   if: (branch = master) OR (branch = stable)
    #   script:
    #     - yarn run release
    #   before_cache:
    #     - rm -rf $HOME/.cache/electron-builder/wine