compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

yarnPath: '.yarn/releases/yarn-berry.cjs'
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: '@yarnpkg/plugin-typescript'
