# This file defines rules for Yarn (2.x)
yarnPath: '.yarn/releases/yarn-berry.cjs'
compressionLevel: 0
enableGlobalCache: true
nodeLinker: node-modules
npmRegistryServer: 'https://registry.yarnpkg.com'

# Hoist only to workspace-level
# https://dev.to/arcanis/yarn-2-3-info-command-detailed-options-nohoist-409h
nmHoistingLimits: workspaces
